image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-compose

stages:
  - build
  - tear

build:
  stage: build
  script:
    - docker-compose up -d

tear:
  stage: tear
  dependencies:
    - build
  script:
    - docker-compose down
